version: "3.9"

services:
  sttm-builder:
    build:
      context: ./services/sttm-builder
    env_file:
      - ./services/sttm-builder/.env.local
    environment:
      PORT: 8000

  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0

  nginx:
    build:
      context: ./nginx
    environment:
      FRONTEND_UPSTREAM: frontend:3000
      BACKEND_UPSTREAM: sttm-builder:8000
    depends_on:
      - sttm-builder
      - frontend
    ports:
      - "8080:8080"
