import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

const ROUTE = "/mappings";

export const mappingsTour: TourDefinition = {
  id: "mappings",
  label: "Mappings",
  description:
    "The All Mappings screen: filtering, sorting, and opening source-to-target mappings across projects.",
  routes: [ROUTE],
  steps: [
    {
      id: "mappings-overview",
      screen: "Mappings",
      title: "All Mappings",
      body: "Every source-to-target mapping across all projects, in one list. Where the Projects screen groups work into folders, this screen is the flat view useful when you know the mapping you want but not the project it lives in.",
      placement: "center",
      route: ROUTE,
    },
    {
      id: "mappings-header",
      screen: "Mappings",
      title: "Mapping Count",
      body: "The count under the title reflects what is currently on screen. As you apply filters it updates, and it names the project when you narrow to a single one so you always know what the list is showing.",
      target: tourSelector(TOUR_TARGETS.mappingsHeader),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-new-mapping",
      screen: "Mappings",
      title: "New Mapping",
      body: "Starts a new source-to-target mapping. You choose how to begin upload SQL, upload an Excel sheet, or build it manually and the mapping is added to the project you have filtered to.",
      target: tourSelector(TOUR_TARGETS.mappingsNewMapping),
      placement: "left",
      route: ROUTE,
    },
    {
      id: "mappings-status-filters",
      screen: "Mappings",
      title: "Status Filters",
      body: "Filter by how far along a mapping is. 'Complete' means every target column is mapped, 'Partial' means some work remains, and 'Draft' means it has been created but no columns are mapped yet. 'All' clears the filter.",
      target: tourSelector(TOUR_TARGETS.mappingsStatusFilters),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-sort",
      screen: "Mappings",
      title: "Sort",
      body: "Reorders the list most recently updated first by default, so work in progress stays at the top.",
      target: tourSelector(TOUR_TARGETS.mappingsSort),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-project-filter",
      screen: "Mappings",
      title: "Project Filter",
      body: "Restricts the list to a single project folder. Opening this screen from a project card on the Projects page applies this filter for you.",
      target: tourSelector(TOUR_TARGETS.mappingsProjectFilter),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-search",
      screen: "Mappings",
      title: "Search Mappings",
      body: "Find a mapping by name. Search combines with the status and project filters rather than replacing them, so you can search within a narrowed list.",
      target: tourSelector(TOUR_TARGETS.mappingsSearch),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-table",
      screen: "Mappings",
      title: "Mappings List",
      body: "Each row is one mapping. The columns cover what it is, what the AI has understood about it, who created it, and when it last changed.",
      target: tourSelector(TOUR_TARGETS.mappingsTable),
      placement: "top",
      route: ROUTE,
    },
    {
      id: "mappings-column-mapping",
      screen: "Mappings",
      title: "Mapping",
      body: "The mapping's name, with its target table underneath 'Target not selected' until you choose one. Below that sit the status badge and the project the mapping belongs to.",
      target: tourSelector(TOUR_TARGETS.mappingsColumnMapping),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-column-ai-summary",
      screen: "Mappings",
      title: "AI Summary",
      body: "A generated description of the mapping's current state: how many rows are mapped out of the total, and whether its semantic bundle has been linked. It lets you judge progress without opening the mapping.",
      target: tourSelector(TOUR_TARGETS.mappingsColumnAiSummary),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-column-created-by",
      screen: "Mappings",
      title: "Created By & Date",
      body: "Who owns the mapping, and when it was last updated shown as both an exact timestamp and a relative age, so recent activity is easy to spot.",
      target: tourSelector(TOUR_TARGETS.mappingsColumnCreatedBy),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "mappings-open-button",
      screen: "Mappings",
      title: "Open",
      body: "Loads the mapping into the STTM Builder, where you select tables, map columns, and publish. It reopens at the step the mapping had reached.",
      target: tourSelector(TOUR_TARGETS.mappingsOpenButton),
      placement: "left",
      route: ROUTE,
    },
    {
      id: "mappings-footer",
      screen: "Mappings",
      title: "Totals & Pagination",
      body: "Totals for the filtered list, broken down into complete, partial, and draft. On the right, set how many mappings appear per page and step through them.",
      target: tourSelector(TOUR_TARGETS.mappingsFooter),
      placement: "top",
      route: ROUTE,
    },
  ],
};
