import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

const ROUTE = "/projects";

export const projectsTour: TourDefinition = {
  id: "projects",
  label: "Projects",
  description:
    "The Projects screen: project folders, mapping coverage, hardcoded values, and creating a project.",
  routes: [ROUTE],
  steps: [
    {
      id: "projects-overview",
      screen: "Projects",
      title: "Projects",
      body: "A project is a folder that groups related source-to-target mappings. This screen shows every project you have access to, each as a card summarising how much of its mapping work is done.",
      placement: "center",
      route: ROUTE,
    },
    {
      id: "projects-header",
      screen: "Projects",
      title: "Project Totals",
      body: "The counts under the title tell you how many project folders exist and how many mappings they hold in total, so you can see the size of the workspace at a glance.",
      target: tourSelector(TOUR_TARGETS.projectsHeader),
      placement: "bottom",
      route: ROUTE,
    },
    {
      id: "projects-new-project",
      screen: "Projects",
      title: "New Project",
      body: "Creates a new project folder. You give it a name, description, and colour, and can link it to existing projects so related migrations stay grouped. After creating it, you are taken straight to its mappings.",
      target: tourSelector(TOUR_TARGETS.projectsNewProject),
      placement: "left",
      route: ROUTE,
    },
    {
      id: "projects-grid",
      screen: "Projects",
      title: "Project Folders",
      body: "Every project appears here as a card. The coloured bar along the top of each card is the project's own colour, which makes a folder easier to recognise as the list grows.",
      target: tourSelector(TOUR_TARGETS.projectsGrid),
      placement: "top",
      route: ROUTE,
    },
    {
      id: "projects-card",
      screen: "Projects",
      title: "Open a Project",
      body: "Click anywhere on a card to open that project and explore the mappings inside it. The card shows the project name and a short description of what the migration covers.",
      target: tourSelector(TOUR_TARGETS.projectsCard),
      placement: "right",
      route: ROUTE,
    },
    {
      id: "projects-card-coverage",
      screen: "Projects",
      title: "Avg. Mapping Coverage",
      body: "The average share of target columns that have been mapped across the project's mappings. 100% means every mapping in the folder has all its target columns mapped; a low value means work is still outstanding.",
      target: tourSelector(TOUR_TARGETS.projectsCardCoverage),
      placement: "right",
      route: ROUTE,
    },
    {
      id: "projects-card-status",
      screen: "Projects",
      title: "Mapping Status",
      body: "These badges break the project down by state: the total number of mappings, plus how many are complete, partial, or still in draft. Badges only appear when that state has mappings in it.",
      target: tourSelector(TOUR_TARGETS.projectsCardStatus),
      placement: "right",
      route: ROUTE,
    },
    {
      id: "projects-card-hardcoded-values",
      screen: "Projects",
      title: "Hardcoded Values",
      body: "Opens the project's hardcoded values the fixed constants and default values its mappings rely on so you can review and maintain them in one place. This opens directly, without entering the project.",
      target: tourSelector(TOUR_TARGETS.projectsCardHardcodedValues),
      placement: "right",
      route: ROUTE,
    },
    {
      id: "projects-card-meta",
      screen: "Projects",
      title: "Created & Last Modified",
      body: "Shows who created the project and who changed it last, with the timestamp useful for knowing who to ask before editing someone else's migration.",
      target: tourSelector(TOUR_TARGETS.projectsCardMeta),
      placement: "right",
      route: ROUTE,
    },
    {
      id: "projects-summary-footer",
      screen: "Projects",
      title: "Workspace Summary",
      body: "The footer totals every project on the screen: projects, total mappings, and how many mappings are complete versus still in progress.",
      target: tourSelector(TOUR_TARGETS.projectsSummaryFooter),
      placement: "top",
      route: ROUTE,
    },
  ],
};
