import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

export const sttmTableSelectionTour: TourDefinition = {
  id: "sttm-table-selection",
  label: "STTM — Select Tables",
  description: "Step 1 of the STTM Builder workflow — select source and target tables.",
  routes: ["/sttm/builder/new", "/sttm/builder/new/"],
  steps: [
    {
      id: "sttm-table-selection-intro",
      screen: "Screen 4",
      title: "Table Selection",
      body: "This is Step 1 of the STTM Builder workflow — Select Tables. The stepper at the top shows the three-step journey: (1) Select Tables → (2) Map · Transform · Validate → (3) Final Mapping & Summary. The left panel is divided into three collapsible sections: Source Selection, Target Selection, and Derived Sources Selection. The user must select at least one source table and one target table before the Next button becomes active.",
      target: tourSelector(TOUR_TARGETS.sttmStepper),
      placement: "bottom",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-source-selection",
      screen: "Screen 4",
      title: "Source Selection",
      body: "Lists all available databases and schemas from the connected source system. The user expands schemas to browse and select tables to use as source inputs in the mapping.",
      target: tourSelector(TOUR_TARGETS.sttmSourceSelection),
      placement: "right",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-target-selection",
      screen: "Screen 4",
      title: "Target Selection",
      body: "Lists all available databases and schemas for selecting the target table. Only one target table can be selected per mapping.",
      target: tourSelector(TOUR_TARGETS.sttmTargetSelection),
      placement: "right",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-derived-sources",
      screen: "Screen 4",
      title: "Derived Sources",
      body: "Displays any derived tables the user has created. A derived table is a temporary SQL-based virtual table built from source tables to produce intermediate columns for mapping.",
      target: tourSelector(TOUR_TARGETS.sttmDerivedSources),
      placement: "right",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-add-derived",
      screen: "Screen 4",
      title: "Add Derived",
      body: "Opens the 'Add Derived Table' modal, where the user can build a derived SQL source by selecting tables, defining joins, and writing or generating a SQL expression.",
      target: tourSelector(TOUR_TARGETS.sttmAddDerived),
      placement: "bottom",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-next-button",
      screen: "Screen 4",
      title: "Next",
      body: "Navigates the user to Step 2 — Map · Transform · Validate. Becomes active only when at least one source table and one target table have been selected.",
      target: tourSelector(TOUR_TARGETS.sttmNextButton),
      placement: "bottom",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-add-join",
      screen: "Screen 4",
      title: "Add Join",
      body: "Adds a new join relationship between selected source tables in the Table Relationships canvas. The user selects the join type: INNER, LEFT, RIGHT, or FULL JOIN.",
      target: tourSelector(TOUR_TARGETS.sttmAddJoin),
      placement: "bottom",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-add-group",
      screen: "Screen 4",
      title: "Add Group",
      body: "Adds a filter group in the Filter Conditions section. The user can define conditions, groupings, and sorting rules to control which rows are included in the mapping output.",
      target: tourSelector(TOUR_TARGETS.sttmAddGroup),
      placement: "bottom",
      route: "/sttm/builder/new",
    },
    {
      id: "sttm-ai-assistant",
      screen: "Screen 4",
      title: "AI Assistant",
      body: "Opens the AI chat window. The user can ask the AI agent for guidance on table selection, join logic, and next steps. Always visible at the bottom-right corner of the screen.",
      target: tourSelector(TOUR_TARGETS.sttmAiAssistant),
      placement: "left",
      route: "/sttm/builder/new",
    },
  ],
};
