import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

export const sttmTablesSelectedTour: TourDefinition = {
  id: "sttm-tables-selected",
  label: "STTM — Tables Selected",
  description: "Source and target tables selected with join relationships.",
  routes: ["/sttm/builder/new"],
  steps: [
    {
      id: "sttm-tables-selected-intro",
      screen: "Screen 5",
      title: "Tables Selected",
      body: "This screen shows the Source Selection step after the user has selected multiple source tables and one target table. The main content area now displays selected tables with their column counts, and the Table Relationships canvas shows the join diagram. The first source table selected is automatically designated as the Driving Table — the anchor table that determines row granularity and join direction (equivalent to the table in the FROM clause of a SQL query). Additional source tables join the driving table.",
      placement: "center",
      route: "/sttm/builder/new",
      requiresState: "tables-selected",
    },
    {
      id: "sttm-driving-badge",
      screen: "Screen 5",
      title: "Driving Badge",
      body: "The orange 'DRIVING' badge indicates this is the current Driving Table. The first table selected is automatically set as the driving table. The user can reassign it using the context menu on another row.",
      target: tourSelector(TOUR_TARGETS.sttmDrivingBadge),
      placement: "bottom",
      route: "/sttm/builder/new",
      requiresState: "tables-selected",
    },
    {
      id: "sttm-selected-source-table",
      screen: "Screen 5",
      title: "Selected Source Table",
      body: "A selected source table is joined to the Driving Table. The row shows the table name, schema path, and column count. The user can deselect it by unchecking the checkbox on the left. Another selected source table. Multiple source tables can be selected and will each appear in the Table Relationships canvas for join configuration.",
      target: tourSelector(TOUR_TARGETS.sttmSelectedSourceTable),
      placement: "bottom",
      route: "/sttm/builder/new",
      requiresState: "tables-selected",
    },
    {
      id: "sttm-add-derived-selected",
      screen: "Screen 5",
      title: "Add Derived",
      body: "Same as in the empty state — opens the Add Derived Table modal to create a SQL-based derived source.",
      target: tourSelector(TOUR_TARGETS.sttmAddDerived),
      placement: "bottom",
      route: "/sttm/builder/new",
      requiresState: "tables-selected",
    },
    {
      id: "sttm-clear-all-source",
      screen: "Screen 5",
      title: "Clear All (Source)",
      body: "Removes all selected source tables and resets the source panel. This also clears all defined joins. Use with caution.",
      target: tourSelector(TOUR_TARGETS.sttmClearAllSource),
      placement: "top",
      route: "/sttm/builder/new",
      requiresState: "tables-selected",
    },
    {
      id: "sttm-clear-all-target",
      screen: "Screen 5",
      title: "Clear All (Target)",
      body: "Removes the currently selected target table and resets the target panel.",
      target: tourSelector(TOUR_TARGETS.sttmClearAllTarget),
      placement: "top",
      route: "/sttm/builder/new",
      requiresState: "tables-selected",
    },
  ],
};
