import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

export const sttmDerivedTableTour: TourDefinition = {
  id: "sttm-derived-table",
  label: "STTM — Add Derived Table",
  description: "Create a SQL-based derived virtual table from source tables.",
  routes: ["/sttm/builder/new"],
  steps: [
    {
      id: "sttm-derived-intro",
      screen: "Screen 6",
      title: "Add Derived Table",
      body: "This screen opens when the user clicks '+ Add Derived' on the Source Selection screen. A derived table is a temporary SQL-based virtual table created from source tables to produce intermediate or calculated columns that need to be mapped to the target. The left panel lists available tables for selection. The right panel shows a live SQL View (code editor) where the derived SQL is generated or written. A Function Library on the far right provides SQL functions organized by category: String, Numeric, Date, Conversion, Logic, and Window.",
      placement: "center",
      isModal: true,
    },
    {
      id: "sttm-derived-source-name",
      screen: "Screen 6",
      title: "Derived Source Name",
      body: "Text input where the user names the derived table (e.g., 'Customer Order Summary'). This name appears in the Derived Sources panel after the derived table is created.",
      target: tourSelector(TOUR_TARGETS.derivedSourceName),
      placement: "right",
      isModal: true,
    },
    {
      id: "sttm-derived-available-tables",
      screen: "Screen 6",
      title: "Available Tables",
      body: "Lists all source tables available for inclusion in the derived table. The user selects tables by checking the radio button next to each name.",
      target: tourSelector(TOUR_TARGETS.derivedAvailableTables),
      placement: "right",
      isModal: true,
    },
    {
      id: "sttm-derived-sql-view-tab",
      screen: "Screen 6",
      title: "SQL View tab",
      body: "Shows the auto-generated SQL SELECT statement for the derived table. The user can also manually edit the SQL here; it updates in real time as selections change.",
      target: tourSelector(TOUR_TARGETS.derivedSqlViewTab),
      placement: "bottom",
      isModal: true,
    },
    {
      id: "sttm-derived-columns-preview-tab",
      screen: "Screen 6",
      title: "Resulting Columns Preview tab",
      body: "Shows a preview of the columns that will be exposed by the derived table. The user can verify that the correct output columns are being produced before applying.",
      target: tourSelector(TOUR_TARGETS.derivedColumnsPreviewTab),
      placement: "bottom",
      isModal: true,
    },
    {
      id: "sttm-derived-function-library",
      screen: "Screen 6",
      title: "Function Library",
      body: "A header panel on the right side of the SQL View listing SQL function categories — String, Numeric, Date, Conversion, Logic, and Window.",
      target: tourSelector(TOUR_TARGETS.derivedFunctionLibrary),
      placement: "left",
      isModal: true,
    },
    {
      id: "sttm-derived-function-panel",
      screen: "Screen 6",
      title: "Function Panel",
      body: "Displays clickable SQL functions within the selected category (e.g., CONCAT, TRIM, DATE_TRUNC). Clicking a function inserts it into the SQL editor at the cursor position.",
      target: tourSelector(TOUR_TARGETS.derivedFunctionPanel),
      placement: "left",
      isModal: true,
    },
    {
      id: "sttm-derived-validate-sql",
      screen: "Screen 6",
      title: "Validate SQL",
      body: "Validates the SQL expression in the SQL View for syntax and logical errors before the derived table is created. Always validate before clicking 'Add Derived Table'.",
      target: tourSelector(TOUR_TARGETS.derivedValidateSql),
      placement: "top",
      isModal: true,
    },
    {
      id: "sttm-derived-add-table",
      screen: "Screen 6",
      title: "Add Derived Table",
      body: "Finalizes and creates the derived table, adding it to the Derived Sources panel on the Source Selection screen. The derived table is now available as a source in the mapping workflow.",
      target: tourSelector(TOUR_TARGETS.derivedAddTable),
      placement: "top",
      isModal: true,
    },
  ],
};
