import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

export const sttmMappingTour: TourDefinition = {
  id: "sttm-mapping",
  label: "STTM — Map, Transform & Validate",
  description: "Step 2 — map target columns to source columns.",
  routes: ["/sttm/builder/new/mapping"],
  steps: [
    {
      id: "sttm-mapping-intro",
      screen: "Screen 7",
      title: "Map, Transform & Validate",
      body: "The active tab shows the main mapping grid where target columns will be mapped to source columns. This is the 2nd step in the Mapping process.",
      placement: "center",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-source-columns-panel",
      screen: "Screen 7",
      title: "Source Columns Panel",
      body: "The left panel lists all source columns from the tables selected in previous steps organized by schema and table. The user can search and click columns to map them to target fields.",
      target: tourSelector(TOUR_TARGETS.sttmSourceColumnsPanel),
      placement: "right",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-target-column",
      screen: "Screen 7",
      title: "Target Column",
      body: "The grid column listing all columns in the target table. Each row represents one target column that needs a source mapping.",
      target: tourSelector(TOUR_TARGETS.sttmTargetColumn),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-sql-preview-tab",
      screen: "Screen 7",
      title: "SQL Preview tab",
      body: "The SQL Preview tab shows the complete SQL generated from the current mapping configuration. This query is built in real time from the source-to-target mappings, joins, filters, and transformation rules defined by the user.",
      target: tourSelector(TOUR_TARGETS.sttmSqlPreviewTab),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-data-preview-tab",
      screen: "Screen 7",
      title: "Data Preview tab",
      body: "See actual data flowing from source to target, based on your current mapping rules.",
      target: tourSelector(TOUR_TARGETS.sttmDataPreviewTab),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-data-lineage-tab",
      screen: "Screen 7",
      title: "Data Lineage tab",
      body: "Visualize how source columns map to your target table. Click any card to expand it.",
      target: tourSelector(TOUR_TARGETS.sttmDataLineageTab),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-auto-map-button",
      screen: "Screen 7",
      title: "Auto Map button",
      body: "Triggers the STTM AI agent to automatically map all source columns to the corresponding target columns. The AI Agent generates mapping suggestions with confidence scores and reasons for each mapping.",
      target: tourSelector(TOUR_TARGETS.sttmAutoMapButton),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-next-mapping",
      screen: "Screen 7",
      title: "Next",
      body: "Proceeds Step 3: Final Mapping and Summary. Active only when the required mappings are complete.",
      target: tourSelector(TOUR_TARGETS.sttmNextButton),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-preprocessing-rule",
      screen: "Screen 7",
      title: "Pre-processing Rule",
      body: "Dropdown to select the transformation rule for this mapping row. Options include Direct, Custom, and various built-in transformations. Clicking the Pre-process button opens the Pre-Processing Rule modal.",
      target: tourSelector(TOUR_TARGETS.sttmPreprocessButton),
      placement: "left",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-description-ai",
      screen: "Screen 7",
      title: "Description (AI)",
      body: "An AI-generated description of the mapping rule, auto-populated after Auto Map. The user can edit this if required.",
      target: tourSelector(TOUR_TARGETS.sttmDescriptionAi),
      placement: "top",
      route: "/sttm/builder/new/mapping",
    },
    {
      id: "sttm-ai-assistant-mapping",
      screen: "Screen 7",
      title: "AI Assistant",
      body: "Opens the STTM AI chat window. Available on every screen of the STTM Builder at the bottom-right corner.",
      target: tourSelector(TOUR_TARGETS.sttmAiAssistant),
      placement: "left",
      route: "/sttm/builder/new/mapping",
    },
  ],
};
