import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

export const sttmSummaryTour: TourDefinition = {
  id: "sttm-summary",
  label: "STTM — Final Mapping & Summary",
  description: "Step 3 — review and publish the final mapping output.",
  routes: ["/sttm/builder/new/summary"],
  steps: [
    {
      id: "sttm-summary-intro",
      screen: "Step 3",
      title: "Final Mapping & Summary",
      body: "This is Step 3 of the STTM Builder workflow: Final Mapping & Summary. The user arrives here after completing the mapping in Step 2. This screen consolidates everything into a final, reviewable STTM Sheet — showing all target columns, their transform rules, source columns, and mapping status in one place.",
      placement: "center",
      route: "/sttm/builder/new/summary",
    },
    {
      id: "sttm-summary-ai-summary",
      screen: "Step 3",
      title: "AI Summary",
      body: "Section header for the left panel, indicating the summary below was generated by AI Agent based on the completed mapping. It consists of summary cards showing Total Mapped, Unmapped, Direct Rules, Transforms, Joins, and Source Tables counts at a glance.",
      target: tourSelector(TOUR_TARGETS.sttmSummaryAiSummary),
      placement: "right",
      route: "/sttm/builder/new/summary",
    },
    {
      id: "sttm-summary-excel",
      screen: "Step 3",
      title: "Excel button",
      body: "Downloads the final STTM sheet as an Excel spreadsheet, including all target columns, source mappings, and transformation rules.",
      target: tourSelector(TOUR_TARGETS.sttmSummaryExcel),
      placement: "bottom",
      route: "/sttm/builder/new/summary",
    },
    {
      id: "sttm-summary-sql",
      screen: "Step 3",
      title: "SQL Button",
      body: "Downloads the final generated SQL query as a file.",
      target: tourSelector(TOUR_TARGETS.sttmSummarySql),
      placement: "bottom",
      route: "/sttm/builder/new/summary",
    },
    {
      id: "sttm-summary-publish-mapping",
      screen: "Step 3",
      title: "Publish Mapping",
      body: "Publishes the entire completed mapping, making it final and available for downstream use.",
      target: tourSelector(TOUR_TARGETS.sttmSummaryPublishMapping),
      placement: "bottom",
      route: "/sttm/builder/new/summary",
    },
  ],
};
