import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

export const sttmPreprocessTour: TourDefinition = {
  id: "sttm-preprocess",
  label: "STTM — Pre-Processing Rule",
  description: "Define a custom SQL transformation for a mapping row.",
  routes: ["/sttm/builder/new/mapping"],
  steps: [
    {
      id: "sttm-preprocess-intro",
      screen: "Pre-processing rule screen",
      title: "Pre-Processing Rule",
      body: "This modal opens when the user clicks the Pre-processing button on any mapping row. It allows the user to define a custom SQL expression to transform the source value before it is written to the target column.",
      placement: "center",
      route: "/sttm/builder/new/mapping",
      isModal: true,
      requiresState: "modal-open",
    },
    {
      id: "sttm-preprocess-source-tables",
      screen: "Pre-processing rule screen",
      title: "Source Tables panel",
      body: "Lists all source tables and their columns available for use in the SQL expression. The user clicks a column name to insert it into the SQL editor at the cursor position.",
      target: tourSelector(TOUR_TARGETS.preprocessSourceTables),
      placement: "right",
      isModal: true,
      requiresState: "modal-open",
    },
    {
      id: "sttm-preprocess-sql-editor",
      screen: "Pre-processing rule screen",
      title: "SQL Preview editor",
      body: "The code editor where the user writes or reviews the SQL transformation expression. The editor provides syntax highlighting and is pre-filled with a template comment on opening.",
      target: tourSelector(TOUR_TARGETS.preprocessSqlEditor),
      placement: "bottom",
      isModal: true,
      requiresState: "modal-open",
    },
    {
      id: "sttm-preprocess-function-library",
      screen: "Pre-processing rule screen",
      title: "Function Library panel",
      body: "A panel on the right listing SQL functions organised by category. Clicking any function inserts it into the SQL editor.",
      target: tourSelector(TOUR_TARGETS.preprocessFunctionLibrary),
      placement: "left",
      isModal: true,
      requiresState: "modal-open",
    },
    {
      id: "sttm-preprocess-function-tabs",
      screen: "Pre-processing rule screen",
      title: "Function category tabs",
      body: "Tabs to filter the Function Library by category: String, Numeric, Date, Conversion, Logic, and Window. Clicking a tab shows the relevant SQL functions.",
      target: tourSelector(TOUR_TARGETS.preprocessFunctionTabs),
      placement: "bottom",
      isModal: true,
      requiresState: "modal-open",
    },
    {
      id: "sttm-preprocess-apply-rule",
      screen: "Pre-processing rule screen",
      title: "Apply Rule",
      body: "Saves the SQL expression and applies it as the pre-processing rule for the selected mapping row. The row's Pre-processing Rule column is updated on the Mapping screen.",
      target: tourSelector(TOUR_TARGETS.preprocessApplyRule),
      placement: "top",
      isModal: true,
      requiresState: "modal-open",
    },
    {
      id: "sttm-preprocess-cancel",
      screen: "Pre-processing rule screen",
      title: "Cancel",
      body: "Closes the Pre-Processing Rule modal without saving any changes. The user is returned to the Mapping screen.",
      target: tourSelector(TOUR_TARGETS.preprocessCancel),
      placement: "top",
      isModal: true,
      requiresState: "modal-open",
    },
  ],
};
