import type { TourDefinition } from "../types/tour.types";
import { TOUR_TARGETS, tourSelector } from "../constants/tour-targets";

export const sttmMappingAutomapTour: TourDefinition = {
  id: "sttm-mapping-automap",
  label: "STTM — After Auto Map",
  description: "Mapping grid after AI auto-mapping is complete.",
  routes: ["/sttm/builder/new/mapping"],
  steps: [
    {
      id: "sttm-automap-intro",
      screen: "Screen 8",
      title: "Mapping Screen (After Auto-Map)",
      body: "This screen shows the Mapping tab after the user has clicked the Auto Map button. The AI Agent has automatically mapped all source columns to target columns. Each mapping row now shows the source column name, a confidence score indicating how certain the AI is about the mapping, and an AI-generated description.",
      target: tourSelector(TOUR_TARGETS.sttmMappingGrid),
      placement: "top",
      route: "/sttm/builder/new/mapping",
      requiresState: "mapping-complete",
    },
    {
      id: "sttm-mapping-progress",
      screen: "Screen 8",
      title: "Mapping progress bar",
      body: "Shows the completion status of the current mapping. The value is displayed with a percentage. Turns fully orange/green when all rows are mapped.",
      target: tourSelector(TOUR_TARGETS.sttmMappingProgress),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
      requiresState: "mapping-complete",
    },
    {
      id: "sttm-confidence-score",
      screen: "Screen 8",
      title: "Confidence score",
      body: "A percentage score shown next to each source column (e.g., 92%, 88%) indicating how confident the AI is in the suggested mapping. Higher scores indicate stronger matches.",
      target: tourSelector(TOUR_TARGETS.sttmConfidenceScore),
      placement: "bottom",
      route: "/sttm/builder/new/mapping",
      requiresState: "mapping-complete",
    },
    {
      id: "sttm-preprocess-button-automap",
      screen: "Screen 8",
      title: "Pre-processing button",
      body: "Opens the Pre-Processing Rule modal for the selected row, allowing the user to write or generate a custom SQL transformation for that mapping.",
      target: tourSelector(TOUR_TARGETS.sttmPreprocessButton),
      placement: "left",
      route: "/sttm/builder/new/mapping",
      requiresState: "mapping-complete",
    },
    {
      id: "sttm-description-ai-automap",
      screen: "Screen 8",
      title: "Description (AI) column",
      body: "The AI-generated description column, auto-filled by STAG after Auto Map with an explanation of why the source column was mapped to the target column.",
      target: tourSelector(TOUR_TARGETS.sttmDescriptionAi),
      placement: "top",
      route: "/sttm/builder/new/mapping",
      requiresState: "mapping-complete",
    },
    {
      id: "sttm-mapped-status",
      screen: "Screen 8",
      title: "Mapped status badge",
      body: "A green 'Mapped' badge appearing in the Status column once a row has a valid source column, pre-processing rule, and order defined. Unmapped rows show an orange 'Unmapped' badge.",
      target: tourSelector(TOUR_TARGETS.sttmMappedStatus),
      placement: "left",
      route: "/sttm/builder/new/mapping",
      requiresState: "mapping-complete",
    },
  ],
};
