-- Least-privilege role split for the canonical semantic registry.
-- Replace the source database/schema grants with the client data domains that the
-- scheduled semantic pipeline is authorized to profile.

GRANT USAGE ON DATABASE FFP_HDP_CRM_MIG_DB_DEV TO ROLE AIA_AGENT_ROLE;
GRANT USAGE ON SCHEMA FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA TO ROLE AIA_AGENT_ROLE;
GRANT USAGE ON PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_SAVE_SEMANTIC_VIEW(VARCHAR)
    TO ROLE AIA_AGENT_ROLE;
GRANT USAGE ON PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_GET_SEMANTIC_ASSET(VARCHAR, VARCHAR, VARCHAR)
    TO ROLE AIA_AGENT_ROLE;
GRANT USAGE ON PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_CHECK_TABLE_STALENESS(VARCHAR, VARCHAR, VARCHAR)
    TO ROLE AIA_AGENT_ROLE;
GRANT USAGE ON PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_CHECK_COLUMN_STALENESS(VARCHAR, VARCHAR, VARCHAR, VARCHAR)
    TO ROLE AIA_AGENT_ROLE;

-- Development fixtures used by the scheduled AGT_SEMANTIC_MODEL_V2 smoke run.
GRANT USAGE ON DATABASE BBI_STTM_TEST_DB TO ROLE AIA_AGENT_ROLE;
GRANT USAGE ON SCHEMA BBI_STTM_TEST_DB.DL_AMOUNT TO ROLE AIA_AGENT_ROLE;
GRANT USAGE ON SCHEMA BBI_STTM_TEST_DB.DW_OPS TO ROLE AIA_AGENT_ROLE;
GRANT SELECT ON TABLE BBI_STTM_TEST_DB.DL_AMOUNT.LOAN_INCOME_AMOUNT_CALCULATION TO ROLE AIA_AGENT_ROLE;
GRANT SELECT ON TABLE BBI_STTM_TEST_DB.DL_AMOUNT.NOTE TO ROLE AIA_AGENT_ROLE;
GRANT SELECT ON TABLE BBI_STTM_TEST_DB.DW_OPS.LOAN_INCOME_AMOUNT_CALCULATION TO ROLE AIA_AGENT_ROLE;
GRANT SELECT ON TABLE BBI_STTM_TEST_DB.DW_OPS.PORTAL_USER_HISTORY TO ROLE AIA_AGENT_ROLE;
GRANT SELECT ON TABLE BBI_STTM_TEST_DB.DW_OPS.WORKFLOW_SESSION TO ROLE AIA_AGENT_ROLE;
GRANT SELECT ON TABLE BBI_STTM_TEST_DB.DW_OPS.WORKFLOW_SESSION_TYPE TO ROLE AIA_AGENT_ROLE;
GRANT SELECT ON TABLE BBI_STTM_TEST_DB.DW_OPS.WORKFLOW_STEP TO ROLE AIA_AGENT_ROLE;

-- The application roles are read-only consumers. They do not receive DML or
-- publication-procedure grants on the three registry tables.
GRANT USAGE ON DATABASE FFP_HDP_CRM_MIG_DB_DEV TO ROLE WORKBENCH_ADMIN;
GRANT USAGE ON SCHEMA FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA TO ROLE WORKBENCH_ADMIN;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SEM_TABLE_VIEWS TO ROLE WORKBENCH_ADMIN;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SEM_COLUMN_VIEWS TO ROLE WORKBENCH_ADMIN;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_SEMANTIC_MODELS TO ROLE WORKBENCH_ADMIN;
GRANT USAGE ON PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_GET_SEMANTIC_ASSET(VARCHAR, VARCHAR, VARCHAR)
    TO ROLE WORKBENCH_ADMIN;

GRANT USAGE ON DATABASE FFP_HDP_CRM_MIG_DB_DEV TO ROLE WORKBENCH_PUBLISHER;
GRANT USAGE ON SCHEMA FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA TO ROLE WORKBENCH_PUBLISHER;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SEM_TABLE_VIEWS TO ROLE WORKBENCH_PUBLISHER;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SEM_COLUMN_VIEWS TO ROLE WORKBENCH_PUBLISHER;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_SEMANTIC_MODELS TO ROLE WORKBENCH_PUBLISHER;
GRANT USAGE ON PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_GET_SEMANTIC_ASSET(VARCHAR, VARCHAR, VARCHAR)
    TO ROLE WORKBENCH_PUBLISHER;

GRANT USAGE ON DATABASE FFP_HDP_CRM_MIG_DB_DEV TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON SCHEMA FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA TO ROLE WORKBENCH_VIEWER;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SEM_TABLE_VIEWS TO ROLE WORKBENCH_VIEWER;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SEM_COLUMN_VIEWS TO ROLE WORKBENCH_VIEWER;
GRANT SELECT ON TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_SEMANTIC_MODELS TO ROLE WORKBENCH_VIEWER;
GRANT USAGE ON PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_GET_SEMANTIC_ASSET(VARCHAR, VARCHAR, VARCHAR)
    TO ROLE WORKBENCH_VIEWER;
