-- Warehouse routing, durable conversation rollover, and content-addressed artifacts.
-- Additive and idempotent for existing client environments.

CREATE TABLE IF NOT EXISTS __STTM_METADATA_NAMESPACE__.TBL_WORKBENCH_CONVERSATION_SEGMENTS (
    SEGMENT_ID STRING NOT NULL,
    LOGICAL_CONVERSATION_ID STRING NOT NULL,
    PHYSICAL_THREAD_ID STRING,
    SEGMENT_NUMBER NUMBER NOT NULL,
    PREVIOUS_SEGMENT_ID STRING,
    NEXT_SEGMENT_ID STRING,
    ROLLOVER_REASON STRING,
    ESTIMATED_CONTEXT_TOKENS NUMBER DEFAULT 0,
    TURN_COUNT NUMBER DEFAULT 0,
    CHECKPOINT_ARTIFACT_ID STRING,
    SEMANTIC_BUNDLE_HASH STRING,
    LEARNING_CONTEXT_HASH STRING,
    STATUS STRING DEFAULT 'ACTIVE',
    USER_ID STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CLOSED_AT TIMESTAMP_NTZ,
    CONSTRAINT PK_WORKBENCH_CONVERSATION_SEGMENTS PRIMARY KEY (SEGMENT_ID)
);

ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS LOGICAL_CONVERSATION_ID STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS CONTEXT_KEY STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS SNAPSHOT_ID STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS RETRIEVED_INFERENCE_IDS VARIANT;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS RETRIEVED_RECOMMENDATION_IDS VARIANT;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS USED_INFERENCE_IDS VARIANT;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS USED_RECOMMENDATION_IDS VARIANT;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS THREAD_SEGMENT NUMBER;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS PROJECT_ID STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS MAPPING_ID STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS MIME_TYPE STRING DEFAULT 'application/json';
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS CONTENT_HASH STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS STAGE_PATH STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS ORIGINAL_SIZE_BYTES NUMBER;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS COMPRESSED_SIZE_BYTES NUMBER;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS SOURCE_ARTIFACT_IDS VARIANT;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS ACCESS_FINGERPRINT STRING;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS SEARCH_KEYWORDS VARIANT;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS RETENTION_UNTIL TIMESTAMP_NTZ;
