CREATE TABLE IF NOT EXISTS FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AUTO_MAP_JOBS (
    JOB_ID                       STRING          NOT NULL,
    REQUEST_ID                   STRING,
    OWNER_ID                     STRING          NOT NULL,
    STATUS                       STRING          NOT NULL,
    STAGE                        STRING,
    CONTEXT_HASH                 STRING,
    SEMANTIC_BUNDLE_ID           STRING,
    AGENT_SPEC_HASHES            VARIANT,
    LEASE_OWNER                  STRING,
    LEASE_EXPIRES_AT             TIMESTAMP_TZ,
    ATTEMPT_COUNT                NUMBER          DEFAULT 0,
    JOB_STATE                    VARIANT         NOT NULL,
    CREATED_AT                   TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT                   TIMESTAMP_TZ    DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT                   TIMESTAMP_TZ    DEFAULT DATEADD('day', 7, CURRENT_TIMESTAMP()),
    CONSTRAINT PK_AUTO_MAP_JOBS PRIMARY KEY (JOB_ID)
)
COMMENT = 'Durable adaptive Auto-map job state, partial results, diagnostics, retries, and replica-safe polling.';

ALTER TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AUTO_MAP_JOBS
    ADD COLUMN IF NOT EXISTS LEASE_OWNER STRING;
ALTER TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AUTO_MAP_JOBS
    ADD COLUMN IF NOT EXISTS LEASE_EXPIRES_AT TIMESTAMP_TZ;
ALTER TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AUTO_MAP_JOBS
    ADD COLUMN IF NOT EXISTS ATTEMPT_COUNT NUMBER DEFAULT 0;
