-- Project-scoped hardcoded values used by mappings and FIR value bindings.
-- Additive and safe for existing client environments.

CREATE TABLE IF NOT EXISTS __STTM_METADATA_NAMESPACE__.TBL_PROJECT_ATTRIBUTES (
    ATTRIBUTE_ID STRING NOT NULL,
    PROJECT_ID STRING NOT NULL,
    ATTRIBUTE_NAME VARCHAR(255) NOT NULL,
    ATTRIBUTE_TYPE VARCHAR(50) NOT NULL,
    ATTRIBUTE_VALUE TEXT,
    SOURCE_PROJECT_ID STRING,
    SOURCE_ATTRIBUTE_ID STRING,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(128),
    UPDATED_BY VARCHAR(128),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PROJECT_ATTRIBUTES PRIMARY KEY (ATTRIBUTE_ID)
)
COMMENT = 'Project-scoped named values available to mappings as governed value bindings.';

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE __STTM_METADATA_NAMESPACE__.TBL_PROJECT_ATTRIBUTES
TO ROLE __SERVICE_OWNER_ROLE__;
