CREATE TABLE IF NOT EXISTS __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACT_JOBS (
    JOB_ID STRING NOT NULL,
    JOB_TYPE VARCHAR(64) NOT NULL,
    REQUEST_ID STRING,
    REQUESTED_BY STRING,
    PROJECT_ID STRING,
    STTM_ID STRING,
    CONTEXT_HASH STRING,
    STATUS VARCHAR(32) NOT NULL DEFAULT 'queued',
    STAGE VARCHAR(64) NOT NULL DEFAULT 'queued',
    REQUEST_PAYLOAD VARIANT,
    RESULT_PAYLOAD VARIANT,
    ERROR_MESSAGE TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STARTED_AT TIMESTAMP_NTZ,
    COMPLETED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_AGENT_ARTIFACT_JOBS PRIMARY KEY (JOB_ID)
)
COMMENT = 'Durable UI job lifecycle for DBT conversion and generated test-case artifacts.';

GRANT SELECT, INSERT, UPDATE
ON TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACT_JOBS
TO ROLE __SERVICE_OWNER_ROLE__;
