-- R13 safe-performance storage only. This migration performs no grants and
-- does not create or alter tasks, streams, agents, stages, or compute objects.

CREATE TABLE IF NOT EXISTS __STTM_METADATA_NAMESPACE__.TBL_WORKBENCH_ASYNC_JOBS (
    JOB_ID STRING NOT NULL,
    IDEMPOTENCY_KEY STRING NOT NULL,
    SNAPSHOT_ID STRING NOT NULL,
    STTM_ID STRING,
    PROJECT_ID STRING,
    JOB_TYPE STRING NOT NULL,
    PAYLOAD VARIANT,
    STATUS STRING NOT NULL DEFAULT 'queued',
    LEASE_OWNER STRING,
    LEASE_EXPIRES_AT TIMESTAMP_NTZ,
    ATTEMPT_COUNT NUMBER NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_DETAILS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ,
    CONSTRAINT PK_WORKBENCH_ASYNC_JOBS PRIMARY KEY (JOB_ID)
)
COMMENT = 'Durable, idempotent post-save jobs with leases and restart-safe retry state.';
