USE DATABASE FFP_HDP_CRM_MIG_DB_DEV;
USE SCHEMA SCH_STTM_METADATA;

-- 1. List databases
CREATE OR REPLACE PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.GET_DATABASES()
RETURNS TABLE (DATABASE_NAME STRING, CREATED TIMESTAMP)
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
  SELECT DATABASE_NAME, CREATED
  FROM SNOWFLAKE.INFORMATION_SCHEMA.DATABASES
  ORDER BY DATABASE_NAME;
$$;

-- 2. List schemas in a given DB
CREATE OR REPLACE PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.GET_SCHEMAS(DB_NAME STRING)
RETURNS TABLE (SCHEMA_NAME STRING, CREATED TIMESTAMP)
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
  SELECT SCHEMA_NAME, CREATED
  FROM IDENTIFIER($DB_NAME || '.INFORMATION_SCHEMA.SCHEMATA')
  ORDER BY SCHEMA_NAME;
$$;

-- 3. List tables in a given DB + schema
CREATE OR REPLACE PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.GET_TABLES(DB_NAME STRING, SCHEMA_NAME STRING)
RETURNS TABLE (TABLE_NAME STRING, TABLE_TYPE STRING, ROW_COUNT NUMBER)
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
  SELECT TABLE_NAME, TABLE_TYPE, ROW_COUNT
  FROM IDENTIFIER($DB_NAME || '.INFORMATION_SCHEMA.TABLES')
  WHERE TABLE_SCHEMA = $SCHEMA_NAME
  ORDER BY TABLE_NAME;
$$;

-- 4. List columns for a given table
CREATE OR REPLACE PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.GET_COLUMNS(DB_NAME STRING, SCHEMA_NAME STRING, TABLE_NAME STRING)
RETURNS TABLE (COLUMN_NAME STRING, DATA_TYPE STRING, IS_NULLABLE STRING, ORDINAL_POSITION NUMBER, COMMENT STRING)
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
  SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, ORDINAL_POSITION, COMMENT
  FROM IDENTIFIER($DB_NAME || '.INFORMATION_SCHEMA.COLUMNS')
  WHERE TABLE_SCHEMA = $SCHEMA_NAME AND TABLE_NAME = $TABLE_NAME
  ORDER BY ORDINAL_POSITION;
$$;