-- Canonical latest-row views for the external semantic registry.
-- Render __SEMANTIC_REGISTRY_NAMESPACE__ from
-- SNOWFLAKE_SEMANTIC_VIEWS_DATABASE.SNOWFLAKE_SEMANTIC_VIEWS_SCHEMA.

CREATE OR REPLACE VIEW __SEMANTIC_REGISTRY_NAMESPACE__.LATEST_TABLE_VIEWS AS
SELECT
    VIEW_ID,
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    FQN,
    GENERATED_AT,
    GENERATED_BY,
    STATUS,
    VERSION,
    ROW_COUNT,
    COLUMN_COUNT,
    COLUMN_SET_HASH,
    LAST_ALTERED_TS,
    SEMANTIC_VIEW
FROM __SEMANTIC_REGISTRY_NAMESPACE__.SEM_TABLE_VIEWS
WHERE UPPER(STATUS) = 'ACTIVE'
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY UPPER(DATABASE_NAME), UPPER(SCHEMA_NAME), UPPER(TABLE_NAME)
    ORDER BY GENERATED_AT DESC, VERSION DESC
) = 1;

CREATE OR REPLACE VIEW __SEMANTIC_REGISTRY_NAMESPACE__.LATEST_COLUMN_VIEWS AS
SELECT
    VIEW_ID,
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    FQN,
    TABLE_VIEW_ID,
    GENERATED_AT,
    GENERATED_BY,
    STATUS,
    DATA_TYPE,
    COLUMN_HASH,
    ATTRIBUTE_VIEW,
    COLUMN_DESCRIPTION
FROM __SEMANTIC_REGISTRY_NAMESPACE__.SEM_COLUMN_VIEWS
WHERE UPPER(STATUS) = 'ACTIVE'
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY UPPER(DATABASE_NAME), UPPER(SCHEMA_NAME), UPPER(TABLE_NAME), UPPER(COLUMN_NAME)
    ORDER BY GENERATED_AT DESC
) = 1;

COMMENT ON VIEW __SEMANTIC_REGISTRY_NAMESPACE__.LATEST_COLUMN_VIEWS IS
    'Latest active column semantic record, including ATTRIBUTE_VIEW and COLUMN_DESCRIPTION.';

CREATE OR REPLACE VIEW __SEMANTIC_REGISTRY_NAMESPACE__.LATEST_NATIVE_VIEWS AS
SELECT
    NATIVE_VIEW_ID,
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    SOURCE_FQN,
    TABLE_VIEW_ID,
    VIEW_NAME,
    TARGET_DB,
    TARGET_SCHEMA,
    TARGET_FQN,
    DDL_TEXT,
    FACTS_COUNT,
    DIMENSIONS_COUNT,
    JOINS_COUNT,
    HAS_LOW_CONFIDENCE_JOINS,
    HAS_FLAGGED_EXCLUDED,
    PK_CONFIRMED,
    PHASE2_ENABLED,
    STATUS,
    CREATED_AT,
    GENERATED_BY,
    ERROR_MESSAGE,
    CA_YAML_MODEL
FROM __SEMANTIC_REGISTRY_NAMESPACE__.SEM_NATIVE_VIEWS
WHERE UPPER(STATUS) = 'ACTIVE'
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY UPPER(DATABASE_NAME), UPPER(SCHEMA_NAME), UPPER(TABLE_NAME)
    ORDER BY CREATED_AT DESC
) = 1;

COMMENT ON VIEW __SEMANTIC_REGISTRY_NAMESPACE__.LATEST_NATIVE_VIEWS IS
    'Latest active native semantic view DDL and Cortex Analyst YAML for each source table.';
