-- ============================================================
-- FIR System Grants
-- SPCS caller-rights grants for FIR system components.
-- ============================================================

-- ============================================================
-- Table Grants
-- ============================================================

-- Grant access to FIR tables for service owner role
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_FIR_360
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_SEMANTIC_VIEW_VERSIONS
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_AGENT_RECOMMENDATIONS
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_WORKSPACE_SNAPSHOTS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_WORKBENCH_CONVERSATION_SEGMENTS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT READ, WRITE ON STAGE __STTM_METADATA_NAMESPACE__.AI_WORKBENCH_ARTIFACTS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_ASSET_TABLE_REFERENCES
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_CONTEXT_EVIDENCE
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_INFERENCE_EVIDENCE
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_INFERENCE_GOALS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_RECOMMENDATION_OUTCOMES
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_FRESHNESS_FEATURES
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_PROFILE_FEATURES
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_CHECKPOINT_DEFINITIONS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_EVIDENCE_ITEMS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_LEARNINGS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_TARGET_MAPPING_PATTERNS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_LEARNING_JOBS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_LEARNING_WORK_ITEMS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_AGENT_BUDGET_LEDGER
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_RECOMMENDATION_ACTION_HISTORY
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_FIR_RUN_OBSERVABILITY
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT, INSERT, UPDATE ON TABLE __STTM_METADATA_NAMESPACE__.TBL_SEMANTIC_BUNDLE_VERSIONS
    TO ROLE __SERVICE_OWNER_ROLE__;


-- ============================================================
-- Stream Grants
-- ============================================================

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_WORKBENCH_FEEDBACK
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_WORKBENCH_EVENTS
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_STTM_ATTRIBUTES
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_DERIVED_SOURCES
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_SEM_TABLE_VIEWS
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_SEM_COLUMN_VIEWS
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_CONVERSATION_TURNS
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_STTM_VERSIONS
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_INFERENCES
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_360_CHANGES
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_CLIENT_SQL_ASSETS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_RECOMMENDATION_OUTCOMES
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_LEARNING_WORK_ITEMS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_PRECOMPUTE_SEM_TABLE_VIEWS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_PRECOMPUTE_SEM_COLUMN_VIEWS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON STREAM __STTM_METADATA_NAMESPACE__.STM_FIR_PRECOMPUTE_SEMANTIC_VERSIONS
    TO ROLE __SERVICE_OWNER_ROLE__;


-- ============================================================
-- View Grants
-- ============================================================

GRANT SELECT ON VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_INFERENCES_SEARCH
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_RECOMMENDATIONS_SEARCH
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT SELECT ON VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_SEMANTIC_VERSIONS_SEARCH
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_RECOMMENDATION_EVIDENCE
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_KNOWLEDGE_SEARCH
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_RUN_OPERATIONS
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT SELECT ON VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_OPERATIONAL_ALERTS
    TO ROLE __SERVICE_OWNER_ROLE__;


-- ============================================================
-- Procedure Grants
-- ============================================================

-- Owner procedures (called by tasks)
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_COLLECT_FEEDBACK()
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_ENRICH_CONTEXT(INTEGER)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_REFRESH_FEATURES(VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_BACKFILL_EVENTS(BOOLEAN, INTEGER)
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_GENERATE_INFERENCES(INTEGER)
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_CREATE_SEMANTIC_VERSION(VARCHAR, VARCHAR)
TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_READ_SEMANTIC_EVIDENCE(VARCHAR, INTEGER)
TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_GENERATE_RECOMMENDATIONS(INTEGER)
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_APPLY_CONFIDENCE_DECAY()
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_ORCHESTRATE_BATCH(VARIANT)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_PROCESS_LEARNING_QUEUE(INTEGER, INTEGER)
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_CONSOLIDATE_SEMANTIC_VERSIONS()
    TO ROLE __SERVICE_OWNER_ROLE__;

-- Agent bridge procedures
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_READ_DOCUMENTS(INTEGER, VARCHAR, VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_INVOKE_AGENT(VARIANT)
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_READ_PENDING_RECORDS(INTEGER, VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_STORE_INFERENCE(VARCHAR, VARCHAR, VARCHAR, VARCHAR, FLOAT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_STORE_RECOMMENDATION(VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, VARCHAR, FLOAT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, VARCHAR, VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_RECONCILE_RECOMMENDATION_IDENTITIES()
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_STORE_QA_PAIR(VARCHAR, VARCHAR, VARCHAR, FLOAT, VARCHAR, VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_MATERIALIZE_DERIVED_SOURCE(VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_PRECOMPUTE_FROM_SEMANTIC_VIEW(VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_PRECOMPUTE_PERMUTATIONS(VARIANT)
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_SCORE_RECOMMENDATIONS()
    TO ROLE __SERVICE_OWNER_ROLE__;

-- Caller procedures (called by other agents)
GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_GET_AGENT_RECOMMENDATIONS(VARCHAR, VARCHAR, VARIANT)
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT USAGE ON PROCEDURE __STTM_METADATA_NAMESPACE__.SP_FIR_RECORD_RECOMMENDATION_SUCCESS(VARCHAR)
    TO ROLE __SERVICE_OWNER_ROLE__;


-- ============================================================
-- Task Grants
-- ============================================================

GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_PROCESS_BATCH
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_CAPTURE
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_ENRICH_CONTEXT
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_PROMOTE_INDEX
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_FRESHNESS_FEATURES
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_PROFILE_FEATURES
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_SEMANTIC_PRECOMPUTE
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_RECOMMENDATION_SCORING
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_CONFIDENCE_DECAY
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT MONITOR, OPERATE ON TASK __STTM_METADATA_NAMESPACE__.TSK_FIR_SEMANTIC_CONSOLIDATION
    TO ROLE __SERVICE_OWNER_ROLE__;


-- ============================================================
-- Cortex Search Service Grants
-- ============================================================

GRANT USAGE ON CORTEX SEARCH SERVICE __STTM_METADATA_NAMESPACE__.CSS_FIR_KNOWLEDGE
    TO ROLE __SERVICE_OWNER_ROLE__;
GRANT USAGE ON CORTEX SEARCH SERVICE __STTM_METADATA_NAMESPACE__.CSS_WORKBENCH_RAG
    TO ROLE __SERVICE_OWNER_ROLE__;


-- ============================================================
-- SPCS Caller-Rights Grants (for executeAsCaller)
-- ============================================================

-- Grant caller usage for SPCS services
GRANT CALLER USAGE ON DATABASE __DATABASE__
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT CALLER USAGE ON SCHEMA __STTM_METADATA_NAMESPACE__
    TO ROLE __SERVICE_OWNER_ROLE__;

GRANT CALLER USAGE ON WAREHOUSE __WAREHOUSE_NAME__
    TO ROLE __SERVICE_OWNER_ROLE__;


-- ============================================================
-- Agent Grants (for AGT_FIR_SYSTEM)
-- ============================================================

GRANT USAGE ON AGENT __STTM_METADATA_NAMESPACE__.AGT_FIR_SYSTEM TO ROLE __SERVICE_OWNER_ROLE__;
