-- Optional helper procedures for agent learning persistence.
-- The application also has a direct table MERGE fallback for restricted clients.

CREATE OR REPLACE PROCEDURE __STTM_METADATA_NAMESPACE__.SP_RECORD_AGENT_LEARNING(
    P_AGENT_TYPE VARCHAR,
    P_LEARNING_TYPE VARCHAR,
    P_SUMMARY VARCHAR,
    P_ATTRIBUTES VARIANT,
    P_ENTITY_TYPE VARCHAR,
    P_ENTITY_IDS VARIANT,
    P_TAGS ARRAY,
    P_CONFIDENCE FLOAT,
    P_CREATED_BY VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_LEARNING_ID VARCHAR DEFAULT 'lrn_' || UUID_STRING();
    V_LEARNING_KEY VARCHAR;
BEGIN
    V_LEARNING_KEY := MD5(
        COALESCE(P_AGENT_TYPE, '') || '|' ||
        COALESCE(P_LEARNING_TYPE, '') || '|' ||
        COALESCE(TO_JSON(P_ATTRIBUTES), '')
    );

    MERGE INTO __STTM_METADATA_NAMESPACE__.TBL_AGENT_LEARNINGS target
    USING (
        SELECT
            :V_LEARNING_ID AS LEARNING_ID,
            :P_AGENT_TYPE AS AGENT_TYPE,
            :P_LEARNING_TYPE AS LEARNING_TYPE,
            :V_LEARNING_KEY AS LEARNING_KEY,
            :P_SUMMARY AS SUMMARY,
            :P_CONFIDENCE AS CONFIDENCE,
            :P_ENTITY_TYPE AS ENTITY_TYPE,
            :P_ENTITY_IDS AS ENTITY_IDS,
            :P_ATTRIBUTES AS ATTRIBUTES,
            :P_TAGS AS TAGS,
            :P_CREATED_BY AS CREATED_BY
    ) source
    ON target.LEARNING_KEY = source.LEARNING_KEY
       AND target.STATUS = 'active'
    WHEN MATCHED THEN UPDATE SET
        SUMMARY = source.SUMMARY,
        CONFIDENCE = GREATEST(
            COALESCE(target.CONFIDENCE, 0),
            source.CONFIDENCE
        ),
        ENTITY_TYPE = COALESCE(source.ENTITY_TYPE, target.ENTITY_TYPE),
        ENTITY_IDS = COALESCE(source.ENTITY_IDS, target.ENTITY_IDS),
        ATTRIBUTES = source.ATTRIBUTES,
        TAGS = COALESCE(source.TAGS, target.TAGS),
        USAGE_COUNT = COALESCE(target.USAGE_COUNT, 0) + 1,
        LAST_USED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        LEARNING_ID, AGENT_TYPE, LEARNING_TYPE, LEARNING_KEY, SUMMARY,
        CONFIDENCE, ENTITY_TYPE, ENTITY_IDS, ATTRIBUTES, TAGS,
        CREATED_BY, STATUS
    ) VALUES (
        source.LEARNING_ID, source.AGENT_TYPE, source.LEARNING_TYPE,
        source.LEARNING_KEY, source.SUMMARY, source.CONFIDENCE,
        source.ENTITY_TYPE, source.ENTITY_IDS, source.ATTRIBUTES,
        source.TAGS, source.CREATED_BY, 'active'
    );

    SELECT LEARNING_ID
      INTO :V_LEARNING_ID
      FROM __STTM_METADATA_NAMESPACE__.TBL_AGENT_LEARNINGS
     WHERE LEARNING_KEY = :V_LEARNING_KEY
       AND STATUS = 'active'
     ORDER BY CREATED_AT DESC
     LIMIT 1;

    RETURN V_LEARNING_ID;
END;
$$;

CREATE OR REPLACE PROCEDURE __STTM_METADATA_NAMESPACE__.SP_TRACK_LEARNING_USAGE(
    P_LEARNING_ID VARCHAR,
    P_WAS_SUCCESSFUL BOOLEAN
)
RETURNS BOOLEAN
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    UPDATE __STTM_METADATA_NAMESPACE__.TBL_AGENT_LEARNINGS
       SET USAGE_COUNT = COALESCE(USAGE_COUNT, 0) + 1,
           SUCCESS_COUNT = COALESCE(SUCCESS_COUNT, 0)
               + IFF(:P_WAS_SUCCESSFUL, 1, 0),
           LAST_USED_AT = CURRENT_TIMESTAMP()
     WHERE LEARNING_ID = :P_LEARNING_ID;
    RETURN TRUE;
END;
$$;
