-- EverNest import/runtime reliability migration.
-- Idempotent DDL only. Data recovery is performed by
-- scripts/recover_evernest_reliability.py after its reconciliation report.
-- Do not combine ADD COLUMN IF NOT EXISTS with DEFAULT: Snowflake explicitly
-- disallows that combination. Runtime reads coalesce nullable legacy rows to
-- FALSE, while the canonical CREATE TABLE DDL retains DEFAULT FALSE for new
-- installations.

ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_PROJECTS
    ADD COLUMN IF NOT EXISTS RUNTIME_SUPPRESSED BOOLEAN;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_PROJECTS
    ADD COLUMN IF NOT EXISTS ARCHIVED_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM
    ADD COLUMN IF NOT EXISTS IMPORT_KEY STRING;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM
    ADD COLUMN IF NOT EXISTS IMPORT_STATE STRING;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM
    ADD COLUMN IF NOT EXISTS RUNTIME_SUPPRESSED BOOLEAN;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM
    ADD COLUMN IF NOT EXISTS SUPERSEDED_BY STRING;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM
    ADD COLUMN IF NOT EXISTS RAW_MAPPING_SQL TEXT;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM
    ADD COLUMN IF NOT EXISTS PARSED_MAPPING_MODEL VARIANT;

ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM_VERSIONS
    ADD COLUMN IF NOT EXISTS RAW_MAPPING_SQL TEXT;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_STTM_VERSIONS
    ADD COLUMN IF NOT EXISTS PARSED_MAPPING_MODEL VARIANT;

ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_WORKSPACE_SNAPSHOTS
    ADD COLUMN IF NOT EXISTS RAW_MAPPING_SQL TEXT;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_WORKSPACE_SNAPSHOTS
    ADD COLUMN IF NOT EXISTS PARSED_MAPPING_MODEL VARIANT;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_WORKSPACE_SNAPSHOTS
    ADD COLUMN IF NOT EXISTS RUNTIME_SUPPRESSED BOOLEAN;

ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_FIR_AGENT_RECOMMENDATIONS
    ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_FIR_AGENT_RECOMMENDATIONS
    ADD COLUMN IF NOT EXISTS PROJECT_ID STRING;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_FIR_AGENT_RECOMMENDATIONS
    ADD COLUMN IF NOT EXISTS STTM_ID STRING;
ALTER TABLE IF EXISTS __STTM_METADATA_NAMESPACE__.TBL_FIR_AGENT_RECOMMENDATIONS
    ADD COLUMN IF NOT EXISTS CHECKPOINT STRING;

-- Snowflake standard-table UNIQUE constraints are informational. Import-key
-- idempotency is therefore also enforced transactionally by the importer.
