from enum import Enum


class ErrorCode(str, Enum):
    # --- Generic ---
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # --- Auth ---
    UNAUTHENTICATED = "UNAUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    OAUTH_TOKEN_EXCHANGE_FAILED = "OAUTH_TOKEN_EXCHANGE_FAILED"

    # --- Validation ---
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # --- Resource ---
    NOT_FOUND = "NOT_FOUND"
    SEMANTIC_ASSET_NOT_FOUND = "SEMANTIC_ASSET_NOT_FOUND"
    SEMANTIC_RELATIONSHIP_INVALID = "SEMANTIC_RELATIONSHIP_INVALID"
    WORKSPACE_CONTEXT_VERSION_UNSUPPORTED = "WORKSPACE_CONTEXT_VERSION_UNSUPPORTED"
    CONTEXT_PRECEDENT_UNAVAILABLE = "CONTEXT_PRECEDENT_UNAVAILABLE"

    # --- Snowflake / Infrastructure ---
    SNOWFLAKE_CONNECTION_ERROR = "SNOWFLAKE_CONNECTION_ERROR"
    SNOWFLAKE_QUERY_ERROR = "SNOWFLAKE_QUERY_ERROR"
    SNOWFLAKE_AGENT_ERROR = "SNOWFLAKE_AGENT_ERROR"
