-- FIR 2.0 generic directed project and mapping precedent links.
-- This migration is intentionally additive and contains no customer-specific data.

CREATE TABLE IF NOT EXISTS __STTM_METADATA_NAMESPACE__.TBL_FIR_PROJECT_LINKS (
    PROJECT_LINK_ID STRING NOT NULL,
    PROJECT_ID STRING NOT NULL,
    PRECEDENT_PROJECT_ID STRING NOT NULL,
    STATUS STRING NOT NULL DEFAULT 'active',
    PRIORITY NUMBER(3, 0) NOT NULL DEFAULT 50,
    KNOWLEDGE_CATEGORIES ARRAY,
    ALLOW_PROJECT_SPECIFIC_VALUES BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FIR_PROJECT_LINKS PRIMARY KEY (PROJECT_LINK_ID),
    CONSTRAINT UQ_FIR_PROJECT_LINKS UNIQUE (PROJECT_ID, PRECEDENT_PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS __STTM_METADATA_NAMESPACE__.TBL_FIR_MAPPING_LINKS (
    MAPPING_LINK_ID STRING NOT NULL,
    STTM_ID STRING NOT NULL,
    PRECEDENT_STTM_ID STRING NOT NULL,
    STATUS STRING NOT NULL DEFAULT 'active',
    PRIORITY NUMBER(3, 0) NOT NULL DEFAULT 75,
    KNOWLEDGE_CATEGORIES ARRAY,
    TARGET_COMPATIBILITY STRING,
    MAPPING_LIFECYCLE STRING,
    PURPOSE STRING,
    CONFIDENCE FLOAT NOT NULL DEFAULT 1.0,
    ALLOW_PROJECT_SPECIFIC_VALUES BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FIR_MAPPING_LINKS PRIMARY KEY (MAPPING_LINK_ID),
    CONSTRAINT UQ_FIR_MAPPING_LINKS UNIQUE (STTM_ID, PRECEDENT_STTM_ID)
);

ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS RETRIEVED_INFERENCE_IDS ARRAY;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS RETRIEVED_RECOMMENDATION_IDS ARRAY;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS USED_INFERENCE_IDS ARRAY;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS USED_RECOMMENDATION_IDS ARRAY;
ALTER TABLE __STTM_METADATA_NAMESPACE__.TBL_AGENT_ARTIFACTS
    ADD COLUMN IF NOT EXISTS RETRIEVAL_EXPLANATIONS VARIANT;

CREATE OR REPLACE VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_ACTIVE_PROJECT_LINKS AS
SELECT
    l.PROJECT_LINK_ID,
    l.PROJECT_ID,
    l.PRECEDENT_PROJECT_ID,
    l.PRIORITY,
    l.KNOWLEDGE_CATEGORIES,
    l.ALLOW_PROJECT_SPECIFIC_VALUES,
    p.PROJECT_NAME AS PRECEDENT_PROJECT_NAME,
    l.CREATED_BY,
    l.CREATED_AT,
    l.UPDATED_AT
FROM __STTM_METADATA_NAMESPACE__.TBL_FIR_PROJECT_LINKS l
LEFT JOIN __STTM_METADATA_NAMESPACE__.TBL_PROJECTS p
    ON TO_VARCHAR(p.PROJECT_ID) = l.PRECEDENT_PROJECT_ID
WHERE LOWER(l.STATUS) = 'active';

CREATE OR REPLACE VIEW __STTM_METADATA_NAMESPACE__.VW_FIR_ACTIVE_MAPPING_LINKS AS
SELECT
    l.MAPPING_LINK_ID,
    l.STTM_ID,
    l.PRECEDENT_STTM_ID,
    l.PRIORITY,
    l.KNOWLEDGE_CATEGORIES,
    l.TARGET_COMPATIBILITY,
    l.MAPPING_LIFECYCLE,
    l.PURPOSE,
    l.CONFIDENCE,
    l.ALLOW_PROJECT_SPECIFIC_VALUES,
    s.PROJECT_ID AS PRECEDENT_PROJECT_ID,
    s.STTM_NAME AS PRECEDENT_STTM_NAME,
    s.TARGET_TABLE AS PRECEDENT_TARGET_TABLE,
    s.STATUS AS PRECEDENT_STATUS,
    l.CREATED_BY,
    l.CREATED_AT,
    l.UPDATED_AT
FROM __STTM_METADATA_NAMESPACE__.TBL_FIR_MAPPING_LINKS l
LEFT JOIN __STTM_METADATA_NAMESPACE__.TBL_STTM s
    ON TO_VARCHAR(s.STTM_ID) = l.PRECEDENT_STTM_ID
WHERE LOWER(l.STATUS) = 'active';
