-- Broad document and conversation retrieval used by Builder and Conversation.
-- FIR exact/contextual retrieval remains separate in CSS_FIR_KNOWLEDGE.
CREATE OR REPLACE CORTEX SEARCH SERVICE __STTM_METADATA_NAMESPACE__.CSS_WORKBENCH_RAG
ON SEARCH_TEXT
PRIMARY KEY (DOC_ID)
ATTRIBUTES
    DOC_FOLDER,
    DOC_TYPE,
    TITLE,
    SEMANTIC_BUNDLE_ID,
    SEMANTIC_VIEW_NAME,
    UPDATED_AT
WAREHOUSE = __WAREHOUSE_NAME__
TARGET_LAG = '1 hour'
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
AS
SELECT
    DOC_ID,
    DOC_FOLDER,
    DOC_TYPE,
    TITLE,
    SEMANTIC_BUNDLE_ID,
    SEMANTIC_VIEW_NAME,
    UPDATED_AT,
    SEARCH_TEXT
FROM __STTM_METADATA_NAMESPACE__.TBL_WORKBENCH_RAG_DOCUMENTS;
