-- Workbench cost and activity dashboard queries.
--
-- ACCOUNT_USAGE views have ingestion latency. These queries intentionally keep
-- warehouse, Cortex Agent/Analyst, and SPCS costs separate because they are
-- independent billing dimensions.

-- 1. Tagged SQL activity by workload, service, endpoint, project and mapping.
--    Workbench query tags are JSON; TRY_PARSE_JSON keeps unrelated queries safe.
WITH tagged_queries AS (
  SELECT
    DATE_TRUNC('hour', START_TIME) AS USAGE_HOUR,
    WAREHOUSE_NAME,
    USER_NAME,
    COALESCE(TRY_PARSE_JSON(QUERY_TAG):workload::STRING, 'untagged') AS WORKLOAD,
    COALESCE(TRY_PARSE_JSON(QUERY_TAG):service::STRING, 'unknown') AS SERVICE,
    COALESCE(TRY_PARSE_JSON(QUERY_TAG):endpoint::STRING, 'unknown') AS ENDPOINT,
    COALESCE(TRY_PARSE_JSON(QUERY_TAG):project::STRING, '') AS PROJECT_ID,
    COALESCE(TRY_PARSE_JSON(QUERY_TAG):mapping::STRING, '') AS MAPPING_ID,
    TOTAL_ELAPSED_TIME,
    EXECUTION_TIME,
    BYTES_SCANNED,
    ROWS_PRODUCED,
    EXECUTION_STATUS
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
  WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
    AND TRY_PARSE_JSON(QUERY_TAG):app::STRING IS NOT NULL
)
SELECT
  USAGE_HOUR,
  WAREHOUSE_NAME,
  USER_NAME,
  WORKLOAD,
  SERVICE,
  ENDPOINT,
  PROJECT_ID,
  MAPPING_ID,
  COUNT(*) AS QUERY_COUNT,
  ROUND(SUM(TOTAL_ELAPSED_TIME) / 1000, 2) AS ELAPSED_SECONDS,
  ROUND(SUM(EXECUTION_TIME) / 1000, 2) AS EXECUTION_SECONDS,
  SUM(BYTES_SCANNED) AS BYTES_SCANNED,
  SUM(ROWS_PRODUCED) AS ROWS_PRODUCED,
  COUNT_IF(EXECUTION_STATUS <> 'SUCCESS') AS FAILED_QUERY_COUNT
FROM tagged_queries
GROUP BY ALL
ORDER BY USAGE_HOUR DESC, QUERY_COUNT DESC;

-- 2. Warehouse credits. Filter WAREHOUSE_NAME to the configured Workbench
--    control, agent, execution and auto-map warehouses in the dashboard.
SELECT
  DATE_TRUNC('hour', START_TIME) AS USAGE_HOUR,
  WAREHOUSE_NAME,
  SUM(CREDITS_USED) AS CREDITS_USED,
  SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
  SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY ALL
ORDER BY USAGE_HOUR DESC, WAREHOUSE_NAME;

-- 3. Cortex Agent token credits by user and agent.
SELECT
  DATE_TRUNC('hour', START_TIME) AS USAGE_HOUR,
  USER_NAME,
  AGENT_NAME,
  COUNT(DISTINCT REQUEST_ID) AS REQUEST_COUNT,
  SUM(TOKENS) AS TOKENS,
  SUM(TOKEN_CREDITS) AS TOKEN_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY ALL
ORDER BY USAGE_HOUR DESC, TOKEN_CREDITS DESC;

-- 4. Cortex Analyst credits by user.
SELECT
  DATE_TRUNC('hour', START_TIME) AS USAGE_HOUR,
  USERNAME,
  SUM(REQUEST_COUNT) AS REQUEST_COUNT,
  SUM(CREDITS) AS CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_ANALYST_USAGE_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY ALL
ORDER BY USAGE_HOUR DESC, CREDITS DESC;

-- 5. SPCS credits by compute pool. This includes the web and auto-map services
--    when they run on separate pools.
SELECT
  DATE_TRUNC('hour', START_TIME) AS USAGE_HOUR,
  COMPUTE_POOL_NAME,
  SUM(CREDITS_USED) AS CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWPARK_CONTAINER_SERVICES_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY ALL
ORDER BY USAGE_HOUR DESC, CREDITS_USED DESC;

-- 6. Detect background traffic that accidentally activates the execution
--    warehouse. Replace the placeholder before running.
SELECT
  START_TIME,
  USER_NAME,
  QUERY_ID,
  QUERY_TEXT,
  QUERY_TAG,
  TOTAL_ELAPSED_TIME,
  EXECUTION_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME = '<EXECUTION_WAREHOUSE>'
  AND COALESCE(TRY_PARSE_JSON(QUERY_TAG):workload::STRING, '') <> 'execution'
ORDER BY START_TIME DESC;
