-- ============================================================
-- PHASE 8: PER-AGENT LEARNING STORAGE WITH CORTEX SEARCH
-- Agent-specific learning storage for better recommendations
-- ============================================================

-- Add AGENT_TYPE column to existing semantic learnings if not exists
-- Note: Run this as an ALTER TABLE if the table already exists

-- Drop and recreate if needed (use ALTER in production)
-- ALTER TABLE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_WORKBENCH_SEMANTIC_LEARNINGS
--   ADD COLUMN IF NOT EXISTS AGENT_TYPE VARCHAR(64) DEFAULT 'GENERAL';

-- Create dedicated agent learnings table
CREATE TABLE IF NOT EXISTS FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS (
    LEARNING_ID         VARCHAR(64)     NOT NULL,
    AGENT_TYPE          VARCHAR(64)     NOT NULL,  -- 'SOURCE_MAPPING', 'TRANSFORMATION_RULE', 'STTM_BUILDER', 'CONVERSATION'
    LEARNING_TYPE       VARCHAR(64)     NOT NULL,  -- 'mapping_acceptance', 'mapping_correction', 'transformation_pattern', etc.
    LEARNING_KEY        VARCHAR(256),              -- For deduplication (hash of key attributes)
    SUMMARY             TEXT            NOT NULL,  -- Human-readable summary for search
    CONFIDENCE          FLOAT           DEFAULT 0.5,
    ENTITY_TYPE         VARCHAR(64),               -- 'mapping_row', 'transformation', 'sttm', 'project'
    ENTITY_IDS          VARIANT,                   -- {project_id, sttm_id, mapping_id, etc.}
    ATTRIBUTES          VARIANT         NOT NULL,  -- Agent-specific learning data
    TAGS                ARRAY,                     -- For filtering: ['pattern:customer_id_mapping', 'rule:CAST', etc.]
    USAGE_COUNT         INTEGER         DEFAULT 0, -- How many times this learning was applied
    SUCCESS_COUNT       INTEGER         DEFAULT 0, -- How many times usage led to acceptance
    LAST_USED_AT        TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          VARCHAR(128),
    STATUS              VARCHAR(32)     DEFAULT 'active',  -- 'active', 'deprecated', 'superseded'
    SUPERSEDED_BY       VARCHAR(64),               -- Learning ID that replaced this one

    CONSTRAINT PK_AGENT_LEARNINGS PRIMARY KEY (LEARNING_ID)
)
COMMENT = 'Per-agent learning storage for specialized recommendations and pattern matching.';

-- Index for fast agent-specific queries
CREATE INDEX IF NOT EXISTS IDX_AGENT_LEARNINGS_TYPE
    ON FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS(AGENT_TYPE, LEARNING_TYPE, STATUS);

CREATE INDEX IF NOT EXISTS IDX_AGENT_LEARNINGS_KEY
    ON FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS(LEARNING_KEY);

-- ============================================================
-- VIEWS FOR CORTEX SEARCH SERVICES
-- ============================================================

-- Source Mapping Agent Learnings View
CREATE OR REPLACE VIEW FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.V_SOURCE_MAPPING_LEARNINGS AS
SELECT
    LEARNING_ID,
    AGENT_TYPE,
    LEARNING_TYPE,
    LEARNING_KEY,
    SUMMARY AS SEARCH_TEXT,
    CONFIDENCE,
    ENTITY_TYPE,
    ENTITY_IDS,
    ATTRIBUTES,
    TAGS,
    USAGE_COUNT,
    SUCCESS_COUNT,
    CASE WHEN USAGE_COUNT > 0 THEN SUCCESS_COUNT::FLOAT / USAGE_COUNT ELSE NULL END AS SUCCESS_RATE,
    CREATED_AT,
    LAST_USED_AT,
    -- Composite score for ranking (confidence + success rate + recency)
    CONFIDENCE * 0.4 +
    COALESCE(CASE WHEN USAGE_COUNT > 0 THEN SUCCESS_COUNT::FLOAT / USAGE_COUNT ELSE 0.5 END, 0.5) * 0.4 +
    (1 - DATEDIFF('day', COALESCE(LAST_USED_AT, CREATED_AT), CURRENT_TIMESTAMP()) / 365.0) * 0.2 AS RELEVANCE_SCORE
FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS
WHERE AGENT_TYPE = 'SOURCE_MAPPING'
  AND STATUS = 'active';

-- Transformation Rule Agent Learnings View
CREATE OR REPLACE VIEW FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.V_TRANSFORMATION_LEARNINGS AS
SELECT
    LEARNING_ID,
    AGENT_TYPE,
    LEARNING_TYPE,
    LEARNING_KEY,
    SUMMARY AS SEARCH_TEXT,
    CONFIDENCE,
    ENTITY_TYPE,
    ENTITY_IDS,
    ATTRIBUTES,
    TAGS,
    USAGE_COUNT,
    SUCCESS_COUNT,
    CASE WHEN USAGE_COUNT > 0 THEN SUCCESS_COUNT::FLOAT / USAGE_COUNT ELSE NULL END AS SUCCESS_RATE,
    CREATED_AT,
    LAST_USED_AT,
    CONFIDENCE * 0.4 +
    COALESCE(CASE WHEN USAGE_COUNT > 0 THEN SUCCESS_COUNT::FLOAT / USAGE_COUNT ELSE 0.5 END, 0.5) * 0.4 +
    (1 - DATEDIFF('day', COALESCE(LAST_USED_AT, CREATED_AT), CURRENT_TIMESTAMP()) / 365.0) * 0.2 AS RELEVANCE_SCORE
FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS
WHERE AGENT_TYPE = 'TRANSFORMATION_RULE'
  AND STATUS = 'active';

-- STTM Builder Agent Learnings View
CREATE OR REPLACE VIEW FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.V_STTM_BUILDER_LEARNINGS AS
SELECT
    LEARNING_ID,
    AGENT_TYPE,
    LEARNING_TYPE,
    LEARNING_KEY,
    SUMMARY AS SEARCH_TEXT,
    CONFIDENCE,
    ENTITY_TYPE,
    ENTITY_IDS,
    ATTRIBUTES,
    TAGS,
    USAGE_COUNT,
    SUCCESS_COUNT,
    CASE WHEN USAGE_COUNT > 0 THEN SUCCESS_COUNT::FLOAT / USAGE_COUNT ELSE NULL END AS SUCCESS_RATE,
    CREATED_AT,
    LAST_USED_AT,
    CONFIDENCE * 0.4 +
    COALESCE(CASE WHEN USAGE_COUNT > 0 THEN SUCCESS_COUNT::FLOAT / USAGE_COUNT ELSE 0.5 END, 0.5) * 0.4 +
    (1 - DATEDIFF('day', COALESCE(LAST_USED_AT, CREATED_AT), CURRENT_TIMESTAMP()) / 365.0) * 0.2 AS RELEVANCE_SCORE
FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS
WHERE AGENT_TYPE = 'STTM_BUILDER'
  AND STATUS = 'active';

-- ============================================================
-- CORTEX SEARCH SERVICES
-- Note: Create these after the views exist
-- ============================================================

-- Source Mapping Agent Search Service
CREATE OR REPLACE CORTEX SEARCH SERVICE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.CSS_SOURCE_MAPPING_LEARNINGS
ON SEARCH_TEXT
ATTRIBUTES LEARNING_ID, AGENT_TYPE, LEARNING_TYPE, CONFIDENCE, USAGE_COUNT, RELEVANCE_SCORE, TAGS, ATTRIBUTES
WAREHOUSE = STTM_BUILDER_WH
TARGET_LAG = '1 hour'
AS (
    SELECT * FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.V_SOURCE_MAPPING_LEARNINGS
);

-- Transformation Rule Agent Search Service
CREATE OR REPLACE CORTEX SEARCH SERVICE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.CSS_TRANSFORMATION_LEARNINGS
ON SEARCH_TEXT
ATTRIBUTES LEARNING_ID, AGENT_TYPE, LEARNING_TYPE, CONFIDENCE, USAGE_COUNT, RELEVANCE_SCORE, TAGS, ATTRIBUTES
WAREHOUSE = STTM_BUILDER_WH
TARGET_LAG = '1 hour'
AS (
    SELECT * FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.V_TRANSFORMATION_LEARNINGS
);

-- STTM Builder Agent Search Service
CREATE OR REPLACE CORTEX SEARCH SERVICE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.CSS_STTM_BUILDER_LEARNINGS
ON SEARCH_TEXT
ATTRIBUTES LEARNING_ID, AGENT_TYPE, LEARNING_TYPE, CONFIDENCE, USAGE_COUNT, RELEVANCE_SCORE, TAGS, ATTRIBUTES
WAREHOUSE = STTM_BUILDER_WH
TARGET_LAG = '1 hour'
AS (
    SELECT * FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.V_STTM_BUILDER_LEARNINGS
);

-- ============================================================
-- HELPER PROCEDURES
-- ============================================================

-- Record a new learning
CREATE OR REPLACE PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_RECORD_AGENT_LEARNING(
    P_AGENT_TYPE VARCHAR,
    P_LEARNING_TYPE VARCHAR,
    P_SUMMARY VARCHAR,
    P_ATTRIBUTES VARIANT,
    P_ENTITY_TYPE VARCHAR DEFAULT NULL,
    P_ENTITY_IDS VARIANT DEFAULT NULL,
    P_TAGS ARRAY DEFAULT NULL,
    P_CONFIDENCE FLOAT DEFAULT 0.7,
    P_CREATED_BY VARCHAR DEFAULT NULL
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_learning_id VARCHAR;
    v_learning_key VARCHAR;
BEGIN
    -- Generate learning ID
    v_learning_id := 'lrn_' || UUID_STRING();

    -- Generate learning key from attributes for deduplication
    v_learning_key := MD5(
        COALESCE(P_AGENT_TYPE, '') || '|' ||
        COALESCE(P_LEARNING_TYPE, '') || '|' ||
        COALESCE(TO_VARCHAR(P_ATTRIBUTES), '')
    );

    -- Check for existing similar learning
    IF EXISTS (
        SELECT 1 FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS
        WHERE LEARNING_KEY = v_learning_key AND STATUS = 'active'
    ) THEN
        -- Update existing learning with higher confidence
        UPDATE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS
        SET
            CONFIDENCE = LEAST(1.0, CONFIDENCE + 0.05),
            USAGE_COUNT = USAGE_COUNT + 1,
            LAST_USED_AT = CURRENT_TIMESTAMP()
        WHERE LEARNING_KEY = v_learning_key AND STATUS = 'active';

        SELECT LEARNING_ID INTO v_learning_id
        FROM FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS
        WHERE LEARNING_KEY = v_learning_key AND STATUS = 'active'
        LIMIT 1;
    ELSE
        -- Insert new learning
        INSERT INTO FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS (
            LEARNING_ID, AGENT_TYPE, LEARNING_TYPE, LEARNING_KEY, SUMMARY,
            CONFIDENCE, ENTITY_TYPE, ENTITY_IDS, ATTRIBUTES, TAGS, CREATED_BY
        ) VALUES (
            v_learning_id, P_AGENT_TYPE, P_LEARNING_TYPE, v_learning_key, P_SUMMARY,
            P_CONFIDENCE, P_ENTITY_TYPE, P_ENTITY_IDS, P_ATTRIBUTES, P_TAGS, P_CREATED_BY
        );
    END IF;

    RETURN v_learning_id;
END;
$$;

-- Track learning usage and success
CREATE OR REPLACE PROCEDURE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.SP_TRACK_LEARNING_USAGE(
    P_LEARNING_ID VARCHAR,
    P_WAS_SUCCESSFUL BOOLEAN DEFAULT TRUE
)
RETURNS BOOLEAN
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_AGENT_LEARNINGS
    SET
        USAGE_COUNT = USAGE_COUNT + 1,
        SUCCESS_COUNT = SUCCESS_COUNT + CASE WHEN P_WAS_SUCCESSFUL THEN 1 ELSE 0 END,
        LAST_USED_AT = CURRENT_TIMESTAMP()
    WHERE LEARNING_ID = P_LEARNING_ID;

    RETURN TRUE;
END;
$$;
