CREATE TABLE IF NOT EXISTS FFP_HDP_CRM_MIG_DB_DEV.SCH_STTM_METADATA.TBL_DERIVED_SOURCES (
    DERIVED_SOURCE_ID STRING,
    DERIVED_SOURCE_NAME STRING,
    SQL_TEXT STRING,
    DRIVING_TABLE STRING,
    SOURCE_TABLES VARIANT,
    RELATIONSHIPS VARIANT,
    FILTERS VARIANT,
    SELECTED_COLUMNS_BY_TABLE VARIANT,
    PREVIEW_COLUMNS VARIANT,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);
