CREATE DATABASE IF NOT EXISTS AI_WORKBENCH_DEV;
CREATE SCHEMA IF NOT EXISTS AI_WORKBENCH_DEV.APP_RUNTIME;
CREATE IMAGE REPOSITORY IF NOT EXISTS AI_WORKBENCH_DEV.APP_RUNTIME.AI_WORKBENCH_DEV_IMAGES;
CREATE STAGE IF NOT EXISTS AI_WORKBENCH_DEV.APP_RUNTIME.AI_WORKBENCH_DEV_DEPLOY_STAGE;
